img_size: 256
encoder_blocks: 4   # Depth of the encoder network (number of residual blocks).
decoder_blocks: 2   # Depth of the decoder network (number of residual blocks).
img_path: "/home/wjj/LIDMark/dataset/image/celeba-hq_256"
wm_path: "/home/wjj/LIDMark/dataset/watermark_152/celeba-hq"
weight_path: "./weights/256_152"

sep_model: false
gpu_ids: "0, 1"
seed: 42    # Global random seed for reproducibility.
encoder_channels: 64
decoder_channels: 64
discriminator_channels: 64
discriminator_blocks: 3
watermark_length: 152   # Dimension of the watermark vector to be embedded (136 landmarks + 16 ID bits).
epochs: 100
batch_size: 16
lr: 4.3e-4    # Learning rate for the optimizer (Adam).
manipulation_mode: "common"
manipulation_layers:
  - "RandomDistortion(['Identity()', 'Resize(0.5)', 'GaussianBlur(2,3)', 'MedBlur(3)', 'JpegTest(50)', 'JpegMask(50)'])"
encoder_weight: 1.97
landmark_loss_weight: 11.5
id_loss_weight: 14.7
discriminator_weight: 0.007
# Settings for periodic validation during training.
validation:
  enable: false
  save_count: 16
# Settings for resuming training from a saved checkpoint.
resume:
  enable: false
  epoch: 0
